config/routes.rb
Twitmemo::Application.routes.draw do
  resources :memos
  root :to => "memos#index"
  # omniauth
  match 'auth/:provider/callback' => 'sessions#login'
  match '/logout' => 'sessions#logout', :as => :logout
  match  '/auth/failure' => "memos#index"

  match '/following' => 'note#index', :as => :following
  match '/user/:screen_name' => 'user#index', :as => :user
  match '/terms' => 'terms#index', :as => :terms
  match '/fav' => 'fav#index', :as => :fav
  match '/api/post' => 'memos#create'
  match '/api/check' => 'memos#check'
  match '/api/following/:id' => 'following#index'
  match '/api/memos/:screen_name' => 'memos#search'
  match '/api/fav' => 'fav#favorite'
end

app/views/layouts/_index.html.erb
<script type="text/javascript">
  $(function() {
    $('#slider').slider({
	   showControls: false,
	   autoplay: true,
	   showPosition: true,
	   hoverPause: true,
	   wait: 8000,
	   fade: 500,
	   direction: "left"
    });
  });
</script>

<div class="alert alert-success">
  <span style="float:left"><%= image_tag "chrome.png", width:"40px", height:"40px"; %></span>
  <strong style="float:left;font-size:15px;margin-top:13px;margin-left:5px;"><a href="TwitmemoExtension.crx">Chrome拡張リリース！いつでもメモでき､Twitterのユーザーページでは情報が自動入力されます！</a></strong>
  <div style="clear:both;"></div>
</div>

  <div class="hero-unit" style="height:160px">
    <div style="float:left; width:440px; margin-top:-33px; margin-left:-20px;">
      <h1>Twitmemo</h1>
      <p>TwitmemoはあなたとTwitterユーザーの出会いを記録するサービスです｡<br/>ユーザーをフォローした理由､印象を忘れる前にメモ｡毎日の素敵な出会いを記録します｡</p>
      <%= link_to "Sign in with Twitter", 'auth/twitter' ,class:"btn btn-large btn-primary"%>
    </div>
    <div style="float:left; margin-left:20px; margin-top:-40px">
      <%= image_tag "logo.png", width:"220px", height:"220px"; %>
    </div>
  </div>

  <div style="width: 780px;">
    <div style="float:left;width:50%">
      <h3 style="margin-bottom:5px;">新着ユーザー</h3>
        <% if @users.present? -%>
          <% @users.each do |user| %>
            <%= link_to user_path(screen_name: user.nickname) do %>
            <img src='<%= user.img %>' width="48px" height="48px">
          <% end %>
        <% end %>
      <% else -%>
        <strong>新着ユーザーはいません｡</strong>
      <% end -%>
    </div>

    <div style="float:left;width:50%">
      <h3 style="margin-bottom:5px;">新着メモ</h3>
      <% if @recentmemos.present? -%>
        <% @recentmemos.each do |memo| %>
          <div style='float:left;'>
            <%= link_to user_path(screen_name: memo.name) do %>
              <img height="48px" width="48px" src="<%= memo.twitter_user.img_url %>">
            <% end %>
          </div>
          <div style='width:250px; float:left; margin-left:1em;margin-top:-5px;'>
            <h4><%= link_to memo.name,user_path(screen_name: memo.name) %><a target="blank" href="http://twitter.com/<%= memo.name %>"><img src="/assets/s_logo.png" width="18px" height="18px" style="margin-left:1px;margin-bottom:-3px;"></a></h4>
              <div style="height:35px; overflow:hidden;margin-bottom:15px;margin-top:3px;">
                <span style="word-break:break-all;"><%= memo.note %></span>
              </div>
          </div>    

          <div style='margin-right:5px;float:right'>
            <%= link_to user_path(screen_name: memo.author_screen_name) do %><img height="24px" width="24px" src="http://img.tweetimag.es/i/<%= memo.author_screen_name %>"><% end %>
          </div>

          <div class="page-header underline" style="margin-right:5px;margin-bottom:14px; padding:0px; clear:both;"></div>
        <% end %>
      <% else -%>
        <strong>新着メモはありません｡</strong>
      <% end -%>
    </div>

    <div id="slider" style="width: 780px; height:170px;clear: both;">
      <div style="margin-top:15px;">
        <div style="float:left;margin-right:30px"><%= image_tag "note.png", width: "120px", height: "120px";  %></div>
          <h3>What is Twitmemo?</h3>
          <p>あの人をフォローした理由が思い出せない時､ありませんか？ そんな時はTwitmemoでユーザーへのメモを残しましょう｡自分がどう評価されているのかチェックすることもできます｡メモの設定を非公開にすればプライベートなメモスペースとしてご利用頂けます｡</p>
      </div>

      <div style="margin-top:15px">
        <div style="float:left; margin-top:-5px;margin-right:35px;"><%= image_tag "twitter.png", width: "120px", height: "120px"; %></div>
          <h3>How to use?</h3>
          <p>メールアドレス､パスワード…面倒な手続きは一切必要ありません｡中央､右上の｢Sign in with Twitter｣ボタンを押すだけ｡Twitterアカウント情報を利用してすぐにサービスを開始できます｡インターネット上での素敵な出会いをメモしましょう｡</p>
        </div>

app/views/layouts/_popup.html.erb
<div id="my-modal" class="modal hide">
	<div class="modal-header">
     <a href="#" class="close">&times;</a>
      <span id="twitter_icon" style="float:left;margin-left:20px;"></span>
      <div class="input-prepend" style="margin-left:8em;height:2.5em;padding-top:1em;">
      	<span class="add-on">@</span>
         <input type="text" maxlength="15" id="input_screen_name" class="span4" style="ime-mode:inactive" placeholder="Twitter ID"/>
      </div>
  </div>

  <div class="modal-body" style="height:9em">
    <textarea id="input_note_area" raws="5" style="width: 520px;height:7em;margin-bottom:5px;" placeholder="フォローした理由は？"></textarea>
  <span id="charactersLeft" style="float:right;font-size:17px;">200</span>
  </div>

  <div class="modal-footer">
    <label  class="checkbox inline">
      <input type="checkbox" name="private" id="private"/><i class="icon-lock"></i>非公開
    </label>
    <label  class="checkbox inline">
      <input type="checkbox" name="twitter" id="twitter"/><i class="icon-comment"></i>Twitterに投稿
    </label>

    <button id="send" data-loading-text="Sending..." class="btn btn-info loading" disabled="TRUE"><i class='icon-edit icon-white'></i> Memo</button>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="span4 sidebar">
  <div class="well">
    <div class="page-header" style="margin:0px 0;margin-bottom:10px;">
      <h3><img src='<%= current_user.img %>'> <%= link_to current_user.name, user_path(screen_name: current_user.nickname) %></h3>
      <span class="label label-warning"><%= link_to "#{memoed_count}メモ", root_path %></span>
      <span class="label label-warning"><%= link_to "#{memo_count}メモられ",user_path(screen_name: current_user.nickname) %></span>
    </div>

    <ul class="nav nav-list">  
      <li><%= link_to root_path do %><i class="icon-home"></i> ホーム<% end %></li>
      <li><a id="open" data-toggle="modal" href="#myModal"><i class="icon-edit"></i> 新規メモ</a></li>
      <li><%= link_to following_path do %><i class="icon-search"></i> フォローからメモ<% end %></li>
      <li><%= link_to fav_path do %><i class="icon-star"></i> お気に入り<% end %></li>
      <li><%= link_to user_path(screen_name: current_user.nickname) do %><i class="icon-user"></i> マイページ<% end %></li>
    </ul>
    <p class="pull-right top"><a href="#top"><i class="icon-arrow-up"></i>Top</a></p>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1&appId=204775049613122";
  fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script>

<div class="container">
  <ul class="navi" style="margin-top:13px;">
    <li style="margin-left:-20px; margin-right:10px;"><h1><%= link_to root_path do %><%= image_tag "twitmemo.png", :width=>"152" %><% end %></h1></li>
    <li style="height:20px;margin-top:0px;">
      <% if current_user -%>
        <%= form_tag(root_path, :method => :get, :class => "form-search") do %>
          <%= search_field_tag :keyword ,nil,:placeholder => "メモ内検索",:class => "input-medium search-query" %>
        <% end -%>
    </li>
    <h4 class="pull-right" style="margin-top:10px;"><%= link_to 'Sign out', logout_path %></h4>

    <% elsif params["controller"] == "memos" && params["action"] == "index" %>
    <div style="float:left; margin-top:6px">
      <ul class="nav">
        <li style="width:100px"><a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja" data-hashtags="twitmemo">ツイート</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></li>
        <li style="width:57px"><a href="http://b.hatena.ne.jp/entry/http://twitmemo.net" class="hatena-bookmark-button" data-hatena-bookmark-title="TwitmemoはあなたとTwitterユーザーの出会いを記録するサービスです" data-hatena-bookmark-layout="standard" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only.gif" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script></li>
        <li><div class="fb-like" data-href="http://twitmemo.net" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div></li>
      </ul>
    </div>
  </ul>
  <h4 class="pull-right" style="margin-top:10px;"><%= link_to 'Sign in', '/auth/twitter' %></h4>
  <% else -%>
    </ul>
    <h4 class="pull-right" style="margin-top:10px;"><%= link_to 'Sign in', '/auth/twitter' %></h4>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="ja">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="TwitmemoはあなたとTwitterユーザーの出会いを記録するサービスです｡ユーザーをフォローした理由､印象を忘れる前にメモ｡毎日の素敵な出会いを記録します｡" />
    <meta name="Keywords" content="Twitmemo,Twitter,memo,note,follow,ツイッター,メモ,ライフログ,マッシュアップ,フォロー,理由,Bootstrap" />
    <title>Twitmemo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <style type="text/css">
      .container{width: 820px;}
      h2{margin:-12px 0px -5px 0px;}
      h4{margin:0px 0px -5px 0px;}
      blockquote{margin-bottom:10px;}
    </style>
  </head>
  <body id="top">
    <div class = "topbar"><%= render 'layouts/topbar' %></div>
    <div class="container">
      <div class="content">
        <noscript>
          <div div class="alert alert-error">
            <strong>このページはJavascriptをオンにしないと正常に動作しません！</strong>
          </div>
        </noscript>
        <% if current_user -%>
          <div class="headerarea"></div> 
          <%= yield %>
          <%= render 'layouts/sidebar' %>
          <%= render 'layouts/popup' %>
        <% else %>
          <%= yield %>
        <% end -%>
      </div>
      <div class="page-header" style="margin-top:0px"></div>
      <div id="footer"><a href="/terms">&copy; Twitmemo 2012</a></div>
    </div>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28885283-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script');
        ga.type ='text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl':'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>